###############
### PLUGINS ###
###############

plugin {
    split-monitor-workspaces {
        keep_focused = 0
        enable_wrapping = 1
        link_monitors = 1
        count = 9
        enable_persistent_workspaces = 1
        monitor_priority = DP-1, HDMI-A-1
    }
}
